forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/mysql'
mod 'erikwebb/drush'
mod 'puppetlabs/apache'
mod 'nodes/php'
mod 'saz/memcached'

mod 'redis',
  :git => 'https://github.com/dol/puppet-redis.git',
  :ref => '6fb86422e7'
